import type { Metadata } from "next";
import { Monda } from "next/font/google";
import "./globals.css";

const monda = Monda({
  variable: "--font-monda",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monda.variable} antialiased gradient-primary`}
      >
        {children}
      </body>
    </html>
  );
}
