import Dexie, { Table } from 'dexie'
import { DateTime } from 'luxon'
import { objectIsCompliant } from "@/utils/index"

interface Params<T> {
  table: string
  model: T
}

export default function useDbCrud<T extends object>({ table, model }: Params<T>) {
  // --- Init DB and table ---
  class DB extends Dexie {
    [table]!: Table
    constructor() {
      super('HabiterDatabase')
      this.version(1).stores({
        [table]: `++id, ${Object.keys(model).join(', ')}, created_at, updated_at, deleted_at` // @id means an id auto-generated by Dexie itself
      })
    }
  }
  const db = new DB()

  // --- DB Operations ---
  const index = async (): Promise<T[]> => {
    const items = await db[table].where('deleted_at').equals(null).all()
    return items
  }
  const show = async (id: string): Promise<T | undefined> => {
    const item = await db[table].where('id').equalsIgnoreCase(id).and('deleted_at').equals(null).first()
    return item
  }
  const store = async (values: Partial<T>): Promise<void> => {
    if(!objectIsCompliant(model, values)) {
      throw new TypeError('Values are not fully compliant with model')
    }
    await db[table].add({
      ...values,
      created_at: DateTime.now().toISO()
    })
  }
  const update = async (id: string, values: Partial<T>): Promise<void> => {
    if(!objectIsCompliant(model, values)) {
      throw new TypeError('Values are not fully compliant with model')
    }
    const item = await show(id)
    if(!item) {
      throw new ReferenceError('Resource could not be found')
    }
    await db[table].put({
      ...item,
      ...values,
      updated_at: DateTime.now().toISO()
    })
  }
  const deleteItem = async(id: string): Promise<void> => {
    const item = await show(id)
    if(!item) {
      throw new ReferenceError('Resource could not be found')
    }
    await db[table].delete(id)
  }

  return {
    index,
    show,
    store,
    update,
    deleteItem
  }
}