import Dexie, { Table } from 'dexie'

interface Params<T> {
  table: string
  model: T
}

export default function useDbCrud<T extends object>({ table, model }: Params<T>) {
  // --- Init DB and table ---
  class DB extends Dexie {
    [table]!: Table
    constructor() {
      super('HabiterDatabase')
      this.version(1).stores({
        [table]: `@id, ${Object.keys(model).join(', ')}, created_at, updated_at` // @id means an id auto-generated by Dexie itself
      })
    }
  }
  const db = new DB()

  // --- DB Operations ---
  const index = async (): Promise<T[]> => {
    const items = await db[table].all()
    return items
  }
  const show = async (id: string): Promise<T | undefined> => {
    const item = await db[table].where('id').equalsIgnoreCase(id).first()
    return item
  }

  return {
    index,
    show
  }
}